---
title: "Clase 23. Modelos de Cambio de Regímen (TAR)"
author: "Benjamin Oliva & Omar Alfaro-Rivera"
date: "30/11/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

### Dependencies and Setup
```{r setup, include = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages('astsa')
#install.packages("tsDyn") #if not yet installed
#
library(astsa)
library(tsDyn)

```

# Data:
Monthly rates of deaths due to flu in the United States for 11 years

```{r echo = FALSE}

flu <- read.delim("flu.txt")

head(flu)

```

# Convert time series

```{r}

flu <- ts(flu)

D_flu = diff(flu, lag = 1)

```

# Plotting

```{r}

plot(flu, type = "b", col = "darkred", ylab = "", 
     main = "Monthly rates of deaths due to flu in the United States")

plot(D_flu, type="b", col = "darkred", ylab = "", 
     main = "Diff Monthly rates of deaths due to flu in the United States")

```

# The tsDyn package in R has simplified this code into a handful of steps:

```{r}

#?setar

D_flu_tar4_05 <- setar(D_flu, m = 4, thDelay = 0, th = 0.05) 

summary(D_flu_tar4_05) 

```

```{r}

plot(D_flu_tar4_05)

```

### If we do not provide a threshold to the th option, setar searches over a grid to choose a threshold ~ 0.038:

```{r}

D_flu_tar4 <- setar(D_flu, m = 4, thDelay = 0)

summary(D_flu_tar4)

plot(D_flu_tar4)

```
